The creator.onShowingProperty function fails when switching to the Translation tab - Uncaught TypeError: options.obj.getType is not a function fix #5869 (#5872)